name = "aiken-lang/options-trading-cardano"
version = "0.0.0"
license = "Apache-2.0"
compiler = "v1.0.29-alpha"
plutus = "v2"
description = "Aiken contracts for project 'aiken-lang/options-trading-cardano'"

[repository]
user = "aiken-lang"
project = "options-trading-cardano"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "1.9.0"
source = "github"
