name = "aiken-lang/options-trading-cardano"
version = "0.0.0"
license = "Apache-2.0"
compiler = "v1.1.2"
plutus = "v3"
description = "Aiken contracts for project 'aiken-lang/options-trading-cardano'"

[repository]
user = "aiken-lang"
project = "options-trading-cardano"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "2.1.0"
source = "github"
